title = "DEVCARNIVAL"
baseURL = "https://example.com/"
languageCode = "en-us"

[params]
  description = "Inspired by the spirit of a true carnival, DevCarnival is a two-day global tech festival in Chennai uniting industry, developers, and academia for purpose-oriented engineering."
  twitter = "#"
  github = "https://github.com/devcarnival"
  linkedin = "https://www.linkedin.com/company/dev-carnival"
  email = "contact@devcarnival.com"

[menu]
  [[menu.main]]
    name = "Sessions"
    url = "/session"
    weight = 1
  [[menu.main]]
    name = "Speakers"
    url = "#speakers"
    weight = 2
  [[menu.main]]
    name = "Community"
    url = "/communities"
    weight = 3
  [[menu.main]]
    name = "Team"
    url = "/team"
    weight = 4
[taxonomies]
  year = "years"
  tag = "tags"
  category = "categories"

[permalinks]
  session = "/session/:slug/"
  communities = "/communities/:slug/"